"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import DeckScene from "./DeckScene";
import "./presentation.css";

type Speaker = "SABRINA" | "KALEB" | "REBEKAH" | "MILA" | "MAX";
type Visual = "title" | "slop" | "promise" | "environment" | "district" | "privacy" | "team" | "close";
type Slide = { speaker:Speaker; chapter:string; title:React.ReactNode; body:React.ReactNode; script:string; seconds:number; visual:Visual; tone:"ink"|"acid"|"paper"|"photo"|"water"; photo?:string; credit?:string };

const team = [
  {name:"Mila",strength:"PROGRAMMING",experience:"Three years on Nevada's top robotics team and three seasons building number-one VRC programs.",impact:"Gave VEGA structure."},
  {name:"Rebekah",strength:"RESEARCH + FLEXIBILITY",experience:"Robotics since sixth grade and creator of a color-detection science-fair app.",impact:"Made VEGA responsible."},
  {name:"Sabrina",strength:"WRITING + PUBLIC SPEAKING",experience:"Speech and Debate secretary, NCL competitor, and County Championship finalist.",impact:"Gave VEGA a voice."},
  {name:"Kaleb",strength:"DESIGN + COLLABORATION",experience:"Multimedia designer, event organizer, cellist, and NCL team competitor.",impact:"Made VEGA stand out."},
  {name:"Max",strength:"MACHINE LEARNING + WEB",experience:"Cyber Club president, systems builder, all-state musician, and top-one-percent NCL competitor.",impact:"Turned five ideas into one prototype."},
];

const slides: Slide[] = [
  {speaker:"SABRINA",chapter:"TEAM VEGA",title:<>Designed here.<br/><em>Built for here.</em></>,body:<><strong>VEGA</strong><p>Five students. One local AI proposal for CCSD.</p></>,script:"Good morning. We are Team VEGA: Sabrina, Kaleb, Rebekah, Mila, and Max. We are five students with different skills, but we kept noticing the same problem. AI is everywhere in education, yet almost none of it was designed specifically for our schools or our community. So we designed something that was.",seconds:20,visual:"title",tone:"photo",photo:"https://images.unsplash.com/photo-1758411623908-6a0edcf866c1?auto=format&fit=crop&fm=jpg&q=82&w=2400",credit:"Las Vegas · Christian Gracia / Unsplash"},
  {speaker:"SABRINA",chapter:"THE PROBLEM",title:<>Ten seconds.<br/><em>Infinite slop.</em></>,body:<><strong>No audience.</strong><strong>No purpose.</strong><strong>The same voice.</strong></>,script:"If you were to pull out your phone right now and scroll on Instagram for ten seconds, it is almost guaranteed that you would come across AI slop. Maybe it is a fake story, a six-fingered person, or that same robotic voice reading a video. It was generated for everyone, which means it was really made for no one. The same problem appears when we use AI for school. We receive generic answers, questionable information, and writing that makes every student sound exactly the same. AI is getting more powerful. But is it actually getting better for us? That question led us to VEGA.",seconds:35,visual:"slop",tone:"photo",photo:"https://fastcdn.impakter.com/wp-content/uploads/2025/12/pexels-ron-lach-9785017-e1765978286137.jpg?avif=80&quality=92&strip=all&webp=92",credit:"Ten seconds of scrolling · Ron Lach / Pexels"},
  {speaker:"SABRINA",chapter:"LIVE PROTOTYPE",title:<>Do not tell them.<br/><em>Show them.</em></>,body:<><p>One student question. One visible privacy check. One answer you can verify.</p><strong className="prototype-proofline">STAGED DEMO RUNS AUTOMATICALLY</strong></>,script:"VEGA is our prototype for an AI platform designed specifically for CCSD. It is not trying to serve every person on Earth. It is designed to serve our students, teachers, and community. Imagine that I missed part of a math lesson. I ask: Can you explain slope without just giving me the answer? VEGA checks the request for private information, guides me through the idea, and shows the trusted sources behind its response. It can support your work without replacing your voice. And unlike a general chatbot, VEGA is built around three priorities: our environment, our district, and our privacy. Kaleb will start with the environment.",seconds:45,visual:"promise",tone:"photo",photo:"https://storage.googleapis.com/cdn.thenevadaindependent.com/2018/11/9eac2aad-gehringacademy111318_019.jpg",credit:"CCSD students · The Nevada Independent"},
  {speaker:"KALEB",chapter:"BUILT FOR LAS VEGAS",title:<>Air, not<br/><em>evaporation.</em></>,body:<><p>A smaller local system designed for one district, not a hyperscale facility built for the world.</p><span className="honesty">ONSITE EVAPORATIVE WATER · 0 PILOT REQUIREMENT</span></>,script:"We live in a desert, so when we hear that AI can consume water for cooling, we should be concerned. These images show how dramatically Lake Mead has changed. Water is not an unlimited resource here. That is why our proposal uses smaller, air-cooled district servers. Fans remove heat from the equipment, so the system would not consume water through evaporative cooling at the site. VEGA will still require electricity. We are not pretending technology has no environmental cost. The difference is scale. VEGA would be a focused system sized for one school district. We designed the infrastructure around the place where it would actually operate. Now Rebekah will show what that could make possible.",seconds:40,visual:"environment",tone:"water",photo:"/lake-mead-change.webp",credit:"Lake Mead change, 2000 to 2022 · image supplied by team"},
  {speaker:"REBEKAH",chapter:"ONE CONNECTED DISTRICT",title:<>Share once.<br/><em>Lift every school.</em></>,body:<><p>Approved lessons, activities, and sources available across CCSD.</p><strong>Less repetition. More collaboration. More consistent support.</strong><span className="evidence-line">ONE TRUSTED RESOURCE LAYER · EVERY SCHOOL · EVERY DEVICE</span></>,script:"CCSD has hundreds of schools and thousands of educators, but teachers often have to solve the same problems separately. One teacher creates a lesson from scratch while another teacher across the district may already have exactly what they need. VEGA could provide a district-controlled space where educators find approved resources, adapt them for their students, and share their own work. It would not tell every teacher to teach in exactly the same way. It would give them a better starting point. That saves time, encourages collaboration, and gives students at different schools more consistent support. A shared system also lets CCSD establish shared protections. Mila will explain why that matters.",seconds:40,visual:"district",tone:"ink",photo:"https://storage.googleapis.com/cdn.thenevadaindependent.com/2023/05/VonTobelVisit_014-2048x1367.jpg",credit:"Von Tobel Middle School · The Nevada Independent"},
  {speaker:"MILA",chapter:"PRIVACY YOU CAN SEE",title:<>Your prompt.<br/><em>Still yours.</em></>,body:<><strong>DISTRICT-CONTROLLED INFRASTRUCTURE</strong><strong>NOT COMMERCIAL TRAINING DATA</strong><strong>SOURCES SHOWN BESIDE ANSWERS</strong><span className="evidence-line">VISIBLE PRIVACY CHECK · VISIBLE SOURCES · VISIBLE LIMITS</span></>,script:"When you enter information into an online AI platform, your request may leave the district and travel through systems controlled by an outside company. With VEGA, the goal is different. The request travels to district-controlled infrastructure and stops there. Student conversations would not be sold to advertisers or used to train a commercial model. CCSD would control access and establish protections designed for its students. We also designed the prototype to show sources beside its answers. VEGA could still make mistakes. Every AI can. The difference is that students and teachers can see where an answer came from and check it. We are not asking anyone to blindly trust AI. We are designing AI that can be questioned.",seconds:40,visual:"privacy",tone:"photo",photo:"https://www.allegromicro.com/-/media/images/insights-and-innovations/blogs/2025/data-center-thermal-management-strategies-1.jpeg?sc_lang=en",credit:"Air-cooled server infrastructure · Allegro MicroSystems"},
  {speaker:"MAX",chapter:"THE DRIVING QUESTION",title:<>Five strengths.<br/><em>One opportunity.</em></>,body:<><span className="driving-question">How can our team use our individual strengths and experiences to create future opportunities?</span><strong className="direct-answer">We combined five different strengths to build one opportunity none of us could create alone.</strong></>,script:"Our driving question was: How can our team use our individual strengths and experiences to create future opportunities? This project is our answer. Mila used her programming experience to give the idea structure. Rebekah researched how VEGA could responsibly support students and teachers. Sabrina turned our research into a message people could understand. Kaleb created the visual identity and made VEGA stand out. I used my experience with machine learning and web design to combine those ideas into the prototype you see today. None of us could have built this alone. Our strengths were different, but that was the reason the project worked.",seconds:40,visual:"team",tone:"photo",photo:"https://storage.googleapis.com/cdn.thenevadaindependent.com/2019/04/7f641ecd-valley-high-school-7-2000x1200.jpg",credit:"Las Vegas students · The Nevada Independent"},
  {speaker:"MAX",chapter:"OUR FUTURE",title:<>Stop accepting.<br/><em>Start creating.</em></>,body:<><p>Test it. Measure it. Improve it.</p><strong>OUR AI. OUR SCHOOLS. OUR FUTURE.</strong></>,script:"VEGA is a prototype. It is not finished, and it is not currently an official CCSD system. But it proves something important. Students do not have to wait for somebody else to decide what the future of education should look like. We can help design it. The next step would be a small pilot using district-controlled hardware, trusted educational sources, and feedback from actual students and teachers. Then we measure it. Is it useful? Is it safe? Does it save teachers time? Does it help students learn? If the answer is no, we improve it. If the answer is yes, we have created something that could reach far beyond the five people standing here. AI is already entering our schools. We can simply accept whatever arrives, or help build something that answers to our community. We choose to build. This is VEGA. Our AI. Our schools. Our future. Thank you. We are ready for your questions.",seconds:40,visual:"close",tone:"photo",photo:"https://images.unsplash.com/photo-1684575571081-d6abda485519?auto=format&fit=crop&fm=jpg&q=82&w=2400",credit:"Las Vegas · Tom Podmore / Unsplash"},
];

const duration = slides.reduce((sum,slide)=>sum+slide.seconds,0);

function VegaMark({large=false}:{large?:boolean}){return <span className={`vega-mark${large?" large":""}`} aria-label="VEGA"><img src="/vega-logo.png" alt=""/><strong>VEGA</strong></span>}
function VegaLogo(){return <div className="student-logo" aria-label="VEGA student logo by Kaleb"><img src="/vega-logo.png" alt="VEGA logo: a graduation cap over a V"/><strong>KALEB&apos;S PROTOTYPE MARK</strong><small>LAS VEGAS · CCSD · STUDENT BUILT</small></div>}
function AppGlyph(){return <span className="app-glyph" aria-hidden="true"><i/><i/></span>}

function TimedCaption({steps,pace=2200}:{steps:string[];pace?:number}){
  const [step,setStep]=useState(0);
  useEffect(()=>{const id=window.setInterval(()=>setStep(value=>(value+1)%steps.length),pace);return()=>window.clearInterval(id)},[pace,steps.length]);
  return <div className="timed-caption" key={`${step}-${steps[step]}`}><i>{String(step+1).padStart(2,"0")}</i><span><small>WHAT IS HAPPENING</small><b>{steps[step]}</b></span><em>{String(steps.length).padStart(2,"0")}</em></div>
}

function TeamSpotlight(){
  const [focus,setFocus]=useState(0);
  useEffect(()=>{const id=window.setInterval(()=>setFocus(value=>(value+1)%team.length),3000);return()=>window.clearInterval(id)},[]);
  const person=team[focus];
  return <div className="team-spotlight">
    <div className="team-cards">{team.map((member,index)=><button key={member.name} className={index===focus?"active":""} onClick={event=>{event.stopPropagation();setFocus(index)}}><i>0{index+1}</i><b>{member.name}</b><span>{member.strength}</span></button>)}</div>
    <article key={person.name}><div><span>NOW SPOTLIGHTING</span><b>{person.name}</b></div><strong>{person.strength}</strong><p>{person.experience}</p><small>{person.impact}</small><em>{String(focus+1).padStart(2,"0")} / 05</em></article>
  </div>
}

function DistrictDemo(){
  const steps=["A teacher searches the shared library","VEGA finds an approved CCSD resource","The teacher adapts it for this class","The improved activity returns to the district"];
  return <div className="visual-stack"><div className="district-demo"><video className="visual-reel" src="/reel-district.mp4" autoPlay muted loop playsInline preload="metadata"/><header><AppGlyph/><b>VEGA RESOURCE EXCHANGE</b><span>CCSD NETWORK</span></header><div className="district-search"><span>⌕</span><p>slope exit ticket for Algebra I</p><i>SEARCH</i></div><div className="district-result"><small>APPROVED RESOURCE</small><b>Graphing Linear Relationships</b><p>Exit ticket · 5 questions · Accessible format</p><div><span>South CTA</span><span>CCSD REVIEWED</span></div></div><div className="district-flow"><span>FIND</span><i>→</i><span>ADAPT</span><i>→</i><span>SHARE</span></div><footer><b>327 SCHOOLS</b><span>ONE TRUSTED STARTING POINT</span></footer></div><TimedCaption steps={steps} pace={2100}/></div>
}

function PrivacyDemo(){
  const steps=["The prompt stays inside the district boundary","VEGA checks for private information","The local model builds a guided response","Sources and limits appear beside the answer"];
  return <div className="visual-stack"><div className="privacy-demo"><video className="visual-reel" src="/reel-privacy.mp4" autoPlay muted loop playsInline preload="metadata"/><header><AppGlyph/><b>VEGA PRIVACY TRACE</b><span><i/> PROTECTED</span></header><section><div className="privacy-device"><small>STUDENT DEVICE</small><b>Explain this assignment</b></div><i>→</i><div className="privacy-core"><span>LOCAL</span><b>CCSD</b><small>PRIVACY CHECK</small></div><i>→</i><div className="privacy-answer"><small>GROUNDED ANSWER</small><b>Guidance + sources</b></div></section><div className="privacy-bar"><span>NO AD NETWORK</span><span>NO COMMERCIAL TRAINING</span><span>NO THIRD-PARTY SALE</span></div><footer><b>REQUEST PATH</b><span>DEVICE → DISTRICT SERVER → STUDENT</span></footer></div><TimedCaption steps={steps} pace={2200}/></div>
}

function PrototypeProof(){
  const [stage,setStage]=useState(1);
  const run=useCallback(()=>{setStage(0);window.setTimeout(()=>setStage(1),80)},[]);
  useEffect(()=>{if(stage===0)return;const delays=stage===1?[1700,2]:stage===2?[1600,3]:stage===3?[2600,4]:null;if(!delays)return;const id=window.setTimeout(()=>setStage(delays[1]),delays[0]);return()=>window.clearTimeout(id)},[stage]);
  return <div className={`staged-demo stage-${stage}`} aria-label="Staged VEGA prototype demonstration">
    <header><span className="demo-brand"><AppGlyph/><b>VEGA</b></span><span><i/> LOCAL PROTOTYPE</span><button onClick={event=>{event.stopPropagation();run()}}>REPLAY</button></header>
    <div className="demo-shell">
      <aside className="demo-modes"><b>MODE</b><strong>✦ Tutor</strong><span>▤ Plan</span><span>文 Translate</span><span>⌁ Navigate</span><small>VIEWING AS<br/><b>STUDENT</b></small></aside>
      <section className="demo-conversation">
        <div className="demo-state"><span>DEMO SEQUENCE</span><b>{stage<2?"RECEIVING QUESTION":stage===2?"CHECKING PRIVACY":stage===3?"BUILDING GUIDANCE":"ANSWER GROUNDED"}</b></div>
        <article className="demo-question"><i>YOU</i><p>Can you explain slope without just giving me the answer?</p></article>
        <div className="demo-check"><i>✓</i><span><b>PRIVACY CHECK PASSED</b><small>No personal information detected</small></span></div>
        <article className="demo-answer"><i>V</i><p><b>Let&apos;s keep the thinking yours.</b><br/>Slope measures how much <strong>y</strong> changes for each 1-unit change in <strong>x</strong>. Choose two points and we will check each step together.</p></article>
      </section>
      <aside className="demo-sources"><b>WHY THIS ANSWER?</b><div><i>✓</i><span><strong>CCSD privacy guidance</strong><small>Protection boundary</small></span></div><div><i>✓</i><span><strong>District learning context</strong><small>Trusted source set</small></span></div><p>Sources stay visible so the answer can be checked.</p></aside>
    </div>
    <footer><span><i/> STAGED DEMO</span><b>QUESTION</b><b>PRIVACY CHECK</b><b>GUIDED ANSWER</b><b>VISIBLE SOURCES</b></footer>
  </div>
}

function Visual({type}:{type:Visual}){
  if(type==="title")return <div className="title-visual"><VegaMark large/><div className="team-list">{["SABRINA","KALEB","REBEKAH","MILA","MAX"].map((name,i)=><span key={name}><i>0{i+1}</i>{name}</span>)}</div></div>;
  if(type==="slop")return <div className="visual-stack"><div className="slop-phone"><div className="phone-top"><span>FOR YOU</span><b>00:10</b></div><div className="slop-feed"><article><i>6?</i><span>TOO MANY FINGERS</span></article><article><i>◎</i><span>SAME FAKE VOICE</span></article><article><i>∞</i><span>NO ONE IN MIND</span></article></div><div className="slop-stamp">MADE BY<br/>NOBODY<br/><b>FOR NOBODY</b></div></div><TimedCaption steps={["The feed rewards speed","The same patterns repeat","Your voice disappears"]} pace={1900}/></div>;
  if(type==="promise")return <PrototypeProof/>;
  if(type==="environment")return <div className="visual-stack"><div className="environment-board"><video className="visual-reel" src="/reel-environment.mp4" autoPlay muted loop playsInline preload="metadata"/><VegaLogo/><div className="airflow" aria-hidden="true">{[0,1,2,3].map(i=><i key={i}/>)}</div><div className="environment-facts"><span><b>FANS</b> move heat</span><span><b>0</b> onsite evaporation</span><span><b>V</b> built for Vegas</span></div></div><TimedCaption steps={["Cool air enters the server rack","Fans carry heat away","No onsite water evaporates"]} pace={2200}/></div>;
  if(type==="district")return <DistrictDemo/>;
  if(type==="privacy")return <PrivacyDemo/>;
  if(type==="team")return <TeamSpotlight/>;
  return <div className="closing-visual"><div className="future-v">V</div><span/><span/><span/><p>OUR AI <i>·</i> OUR SCHOOLS <i>·</i> OUR FUTURE</p></div>;
}

export default function Home(){
  const [active,setActive]=useState(0);const [notes,setNotes]=useState(false);const [playing,setPlaying]=useState(false);const [started,setStarted]=useState(false);const [intro,setIntro]=useState<"ready"|"playing"|"hold"|"done">("ready");const [remaining,setRemaining]=useState(duration);const touchStart=useRef(0);const slide=slides[active];const elapsed=duration-remaining;
  const timeline=useMemo(()=>Math.max(0,Math.min(100,elapsed/duration*100)),[elapsed]);
  const go=useCallback((next:number)=>{const target=Math.max(0,Math.min(slides.length-1,next));if(target===active)return;document.documentElement.dataset.slideDirection=target>active?"forward":"back";const doc=document as Document&{startViewTransition?:(update:()=>void)=>void};if(doc.startViewTransition)doc.startViewTransition(()=>setActive(target));else setActive(target)},[active]);
  const startPresentation=useCallback(()=>{setActive(0);setRemaining(duration);setNotes(false);setPlaying(false);setStarted(false);setIntro("playing");document.documentElement.requestFullscreen?.().catch(()=>{})},[]);
  const finishIntro=useCallback(()=>{setIntro("done");window.setTimeout(()=>{setStarted(true);setPlaying(true)},650)},[]);
  const rampIntro=useCallback((event:React.SyntheticEvent<HTMLVideoElement>)=>{const video=event.currentTarget;if(video.currentTime<8.35)return;if(video.currentTime>=9.66){video.pause();setIntro("hold");return}const progress=(video.currentTime-8.35)/1.31;video.playbackRate=Math.max(.06,1-progress*.94)},[]);
  useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setRemaining(value=>{if(value<=1){setPlaying(false);return 0}return value-1}),1000);return()=>window.clearInterval(id)},[playing]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(intro==="ready"&&event.key==="Enter"){event.preventDefault();startPresentation();return}if(intro==="hold"&&["Enter"," ","ArrowRight","ArrowDown","PageDown"].includes(event.key)){event.preventDefault();finishIntro();return}if(!started)return;if(["ArrowRight","ArrowDown","PageDown"," "].includes(event.key)){event.preventDefault();go(active+1)}if(["ArrowLeft","ArrowUp","PageUp"].includes(event.key))go(active-1);if(event.key.toLowerCase()==="n")setNotes(value=>!value);if(event.key.toLowerCase()==="f")document.documentElement.requestFullscreen?.();if(event.key.toLowerCase()==="r"){setRemaining(duration);setActive(0);setPlaying(false);setStarted(false);setIntro("ready")}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[active,finishIntro,go,intro,started,startPresentation]);
  return <main className={`deck tone-${slide.tone}`} onTouchStart={event=>touchStart.current=event.touches[0].clientX} onTouchEnd={event=>{const distance=event.changedTouches[0].clientX-touchStart.current;if(Math.abs(distance)>55)go(active+(distance<0?1:-1))}}>
    <DeckScene slide={active}/><div className="deck-noise"/>
    <header className="deck-topbar"><span className="deck-wordmark">VEGA <i>CCSD LOCAL AI</i></span><div className="single-mode"><b>{started?"LIVE":"READY"}</b><span>5 MINUTE PRESENTATION</span></div><div className="deck-actions"><Link href="/prototype">EXPLORE FULL PROTOTYPE ↗</Link><button onClick={()=>document.documentElement.requestFullscreen?.()} aria-label="Enter fullscreen">⛶</button></div></header>
    <section key={active} className={`deck-slide slide-${active+1}`} onClick={event=>{const target=event.target as HTMLElement;if(!target.closest("a,button,.speaker-note"))go(active+1)}}>
      {slide.photo&&<div className="slide-photo"><img src={slide.photo} alt=""/><i/><small>{slide.credit}</small></div>}
      <div className="slide-copy"><div className="chapter-label">{slide.chapter}</div><div className="slide-meta"><span>{String(active+1).padStart(2,"0")} / {String(slides.length).padStart(2,"0")}</span><b>{slide.speaker}</b></div><h1>{slide.title}</h1><div className="slide-body">{slide.body}</div></div>
      <div className="slide-graphic"><Visual type={slide.visual}/></div>
      {notes&&<aside className="speaker-note"><div><span>{slide.speaker}</span><b>FULL SCRIPT</b></div><p>{slide.script}</p></aside>}
    </section>
    <footer className="deck-controls"><div className="time"><button onClick={()=>setPlaying(value=>!value)} aria-label={playing?"Pause timer":"Start timer"}>{playing?"Ⅱ":"▶"}</button><b>{String(Math.floor(remaining/60)).padStart(2,"0")}:{String(remaining%60).padStart(2,"0")}</b><span>{playing?"LIVE":"READY"}</span></div><div className="slide-dots">{slides.map((item,i)=><button key={item.chapter} className={i===active?"active":i<active?"past":""} onClick={()=>go(i)} aria-label={`Go to slide ${i+1}`}><i/><span>{item.speaker}</span></button>)}</div><div className="nav-buttons"><button onClick={()=>setNotes(value=>!value)} className={notes?"active":""}>N · SCRIPT</button><button onClick={()=>go(active-1)} disabled={active===0}>←</button><b>{String(active+1).padStart(2,"0")} / {String(slides.length).padStart(2,"0")}</b><button onClick={()=>go(active+1)} disabled={active===slides.length-1}>→</button></div><i className="timeline"><span style={{width:`${timeline}%`}}/></i></footer>
    {intro==="ready"&&<div className="launch-screen" onClick={event=>event.stopPropagation()}><div className="launch-card"><span className="launch-kicker">VEGA PRESENTATION SYSTEM</span><VegaMark large/><h2>Everything is staged.<br/><em>You control the story.</em></h2><p>One click plays the silent ten-second opening, reveals the title, starts the five-minute timer, and hands slide control to you.</p><button onClick={startPresentation}><span>START PRESENTATION</span><i>→</i></button><small>PRESS ENTER TO START · R TO RESET · N FOR SPEAKER SCRIPT</small></div></div>}
    {(intro==="playing"||intro==="hold"||(!started&&intro==="done"))&&<div className={`cinematic-intro ${intro==="hold"?"holding":""} ${intro==="done"?"finishing":""}`} onClick={event=>{event.stopPropagation();if(intro==="hold")finishIntro()}}><video src="/vega-intro.mp4" poster="/vega-intro-poster.jpg" autoPlay muted playsInline onTimeUpdate={rampIntro} onEnded={()=>setIntro("hold")} onError={()=>setIntro("hold")}/><div className="cinematic-shade"/><div className="cinematic-scan"/><div className="cinematic-title"><span>CCSD LOCAL INTELLIGENCE</span><div className="cinematic-name"><b>V</b><strong>VEGA</strong></div><p>DESIGNED HERE <i/> BUILT FOR HERE</p><div className="cinematic-team"><span>SABRINA</span><span>KALEB</span><span>REBEKAH</span><span>MILA</span><span>MAX</span></div></div><div className="cinematic-progress"><span/><small>{intro==="hold"?"PRESS SPACE TO BEGIN":"INITIALIZING PRESENTATION"}</small></div><button onClick={event=>{event.stopPropagation();if(intro==="hold")finishIntro();else setIntro("hold")}}>{intro==="hold"?"BEGIN PRESENTATION":"SKIP TO TITLE"}</button></div>}
  </main>;
}
