"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import DeckScene from "./DeckScene";
import "./presentation.css";

type Mode = "pitch" | "presentation";
type Speaker = "MAX" | "MILA" | "SABRINA" | "REBEKAH" | "KALEB" | "ALL FIVE";
type Slide = { speaker:Speaker; eyebrow:string; title:React.ReactNode; short:React.ReactNode; long:React.ReactNode; note:string; source?:{label:string;url:string}; tone?:"ink"|"paper"|"acid"|"photo"|"water"; photo?:string; credit?:string; visual?:"slop"|"truth"|"local"|"water"|"uses"|"guardrails"|"team"|"close" };

const slides: Slide[] = [
  {speaker:"MAX",eyebrow:"01 / THE OPEN",tone:"ink",title:<>The AI decision<br/><em>is already here.</em></>,short:<>Pull out your phone. Scroll for ten seconds.</>,long:<>Two modes. One idea: students should have a voice in the AI infrastructure that will shape their education.</>,note:"Hold five full seconds of silence. Do not fill it. Look up, then advance."},
  {speaker:"MAX",eyebrow:"02 / THE PROBLEM",tone:"acid",visual:"slop",title:<>SLOP.</>,short:<>Six fingers. The same fake voice. Content made by nobody, for nobody—pushed at you anyway.</>,long:<>Merriam-Webster chose “slop” as its 2025 Word of the Year: low-quality digital content produced in quantity with AI. AI built for attention gives us volume, not value.</>,note:"Land the word first. Then slow down on: “built to farm your attention.”",source:{label:"Merriam-Webster · 2025 Word of the Year",url:"https://www.merriam-webster.com/wordplay/word-of-the-year"}},
  {speaker:"MILA",eyebrow:"03 / THE REALITY",tone:"photo",title:<>AI is already<br/><em>in the building.</em></>,short:<>The argument about whether students will use AI is over.</>,long:<>Education accounts can already access Gemini with administrator controls. The useful question is no longer “AI or no AI?” It is: what should a school-controlled alternative do differently?</>,note:"Do not attack teachers or the district. Establish that the choice is about architecture and control.",source:{label:"Google · Gemini for Education",url:"https://support.google.com/a/answer/16350447?hl=en"},photo:"https://storage.googleapis.com/cdn.thenevadaindependent.com/2023/05/VonTobelVisit_014-2048x1367.jpg",credit:"Von Tobel Middle School · The Nevada Independent"},
  {speaker:"MILA",eyebrow:"04 / THE HONEST COMPARISON",tone:"paper",visual:"truth",title:<>This is not a<br/><em>gotcha.</em></>,short:<>Google says school Workspace prompts are not used to train outside-domain models without permission.</>,long:<>That protection matters—and VEGA should not pretend otherwise. The difference we propose is operational ownership: inference on district-controlled hardware, district-set retention, local auditability, and less dependence on a vendor connection.</>,note:"This is the credibility slide. Say: “We checked. Here is what Google actually promises.”",source:{label:"Google Workspace · Generative AI Privacy Hub",url:"https://knowledge.workspace.google.com/admin/generative-ai/generative-ai-in-google-workspace-privacy-hub"}},
  {speaker:"SABRINA",eyebrow:"05 / THE IDEA",tone:"ink",visual:"local",title:<>Bring the model<br/><em>inside the district.</em></>,short:<>Student → school network → district server → answer.</>,long:<>VEGA is a proposal for AI inference on hardware the district operates. A measured pilot could start with one school, approved sources, no student-record integration, and a clear kill switch.</>,note:"Attach the consequence: our work does not need to leave district-controlled infrastructure to get an answer."},
  {speaker:"SABRINA",eyebrow:"06 / THE WATER QUESTION",tone:"water",visual:"water",title:<>No evaporative<br/><em>cooling.</em></>,short:<>Specify an air-cooled pilot. No onsite water evaporated to answer a prompt.</>,long:<>Southern Nevada Water Authority reports that its evaporative-cooling moratorium went into effect during fiscal year 2023–24. VEGA’s pilot specification follows that direction: small, air-cooled hardware with measured power and heat.</>,note:"Say “onsite water.” Do not claim the entire technology lifecycle uses literally zero water.",source:{label:"SNWA · April 25, 2024 board materials",url:"https://www.snwa.com/universal/agenda/getfile.cfml?id=4728"},photo:"https://images.unsplash.com/photo-1564855009587-fe17bbb8f093?auto=format&fit=crop&w=2200&q=88",credit:"Lake Mead · Nikola Majksner / Unsplash"},
  {speaker:"REBEKAH",eyebrow:"07 / WHAT IT DOES",tone:"paper",visual:"uses",title:<>Useful on<br/><em>Monday morning.</em></>,short:<>Explain the math. Start the essay. Find tomorrow’s work. Cite the official source.</>,long:<>Four modes keep the interaction clear: Tutor asks before answering; Plan breaks work into steps; Translate preserves meaning; Navigate routes users to trusted CCSD systems. The prototype already demonstrates all four.</>,note:"Click a prompt to run the mini demo, or open the full prototype if the room allows it."},
  {speaker:"REBEKAH",eyebrow:"08 / THE RULES",tone:"ink",visual:"guardrails",title:<>Helpful.<br/><em>Not in charge.</em></>,short:<>No automatic grades. No discipline decisions. No pretending uncertainty is fact.</>,long:<>VEGA should block obvious sensitive information, cite official sources, show uncertainty, preserve educator judgment, and escalate safety concerns to qualified people. Every pilot rule should be visible and testable.</>,note:"Prove that local does not automatically mean safe. Safety has to be designed and evaluated.",source:{label:"CCSD · Acceptable Use Policy",url:"https://www.ccsd.net/legal/acceptable-use-policy"}},
  {speaker:"KALEB",eyebrow:"09 / WHY US",tone:"photo",visual:"team",title:<>The code is<br/><em>the easy part.</em></>,short:<>Design. Writing. Research. Engineering. The courage to get a district to say yes.</>,long:<>A credible school AI takes more than a model: interface design, policy research, technical prototyping, evaluation, training, and communication. That is why this is a five-person project—not a chatbot wrapper.</>,note:"Each person steps forward half a pace as their discipline appears.",photo:"https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=2200&q=88",credit:"Student team · Unsplash"},
  {speaker:"MAX",eyebrow:"10 / THE CHOICE",tone:"ink",visual:"close",title:<>Our AI.<br/>Our servers.<br/><em>Our data.</em></>,short:<>You have four more years in this building. This is the moment to ask whose AI they will be.</>,long:<>Start with one transparent, air-cooled pilot. Test learning value, safety, reliability, cost, and trust. Publish the results. Let students and educators decide what deserves to scale.</>,note:"Max says “VEGA.” Everyone breathes together. Then all five deliver the three beats in unison."},
];

const demoPrompts = [["Explain slope","Start with two points. What changes first: x or y? Let’s calculate one step together."],["Plan my essay","Choose one claim you can defend. Then we’ll build three evidence slots around it."],["What is due?","I’d check Canvas first, then Campus for grades. I’ll link the official CCSD systems."]];

function Mark(){return <span className="deck-mark" aria-label="VEGA"><i><b/><b/></i><strong>VEGA</strong></span>}

function Graphic({type,mode}:{type?:Slide["visual"];mode:Mode}){
  const [demo,setDemo]=useState(0);
  if(type==="slop")return <div className="slop-grid" aria-hidden="true"><span>SIX</span><span>Ⅵ</span><span>6?</span><span>404</span><b>CONTENT<br/>WITHOUT<br/>INTENT</b></div>;
  if(type==="truth")return <div className="truth-card"><span>THE CLAIM</span><p>“Your school prompts train the model.”</p><i>NOT SUPPORTED</i><span>THE STRONGER CASE</span><p>Local infrastructure creates local control.</p><b>VERIFIED</b></div>;
  if(type==="local")return <div className="local-map"><div><i>01</i><b>STUDENT</b><small>prompt</small></div><span>→</span><div><i>02</i><b>SCHOOL NETWORK</b><small>protected route</small></div><span>→</span><div className="rack-mini"><i>03</i><b>DISTRICT SERVER</b><small>local inference</small><em/><em/><em/></div><span>→</span><div><i>04</i><b>ANSWER</b><small>source attached</small></div></div>;
  if(type==="water")return <div className="water-stat"><span>ON-SITE EVAPORATIVE WATER</span><strong>0</strong><b>pilot requirement</b><i>fans, not evaporation</i></div>;
  if(type==="uses")return <div className="mini-demo"><div className="demo-tabs">{demoPrompts.map((p,i)=><button key={p[0]} className={demo===i?"active":""} onClick={()=>setDemo(i)}>{p[0]}</button>)}</div><div className="demo-answer"><Mark/><p>{demoPrompts[demo][1]}</p></div><Link href="/prototype">OPEN FULL PROTOTYPE ↗</Link></div>;
  if(type==="guardrails")return <div className="guard-grid">{[["01","SOURCE","Show where answers came from"],["02","PRIVACY","Catch sensitive-data patterns"],["03","HUMAN","Keep judgment with educators"],["04","LIMITS","Say when the model is unsure"]].map(x=><div key={x[0]}><i>{x[0]}</i><b>{x[1]}</b><span>{x[2]}</span></div>)}</div>;
  if(type==="team")return <div className="team-strip">{["MAX","MILA","SABRINA","REBEKAH","KALEB"].map((n,i)=><div key={n}><span>0{i+1}</span><b>{n}</b><i>{["STORY","DESIGN","RESEARCH","TRUST","BUILD"][i]}</i></div>)}</div>;
  if(type==="close")return <div className="close-orbit" aria-hidden="true"><span/><span/><span/><b>✦</b></div>;
  return mode==="presentation"?<div className="opening-manifest"><span>2 MIN</span><i>/</i><span>10 MIN</span><b>ONE STORY</b></div>:<div className="opening-manifest"><span>10</span><b>SLIDES · 120 SECONDS</b></div>;
}

export default function Home(){
  const [mode,setMode]=useState<Mode>("pitch"); const [active,setActive]=useState(0); const [notes,setNotes]=useState(false); const [playing,setPlaying]=useState(false); const [remaining,setRemaining]=useState(120); const touchStart=useRef(0);
  const duration=mode==="pitch"?120:600, slide=slides[active], elapsed=duration-remaining;
  const timeline=useMemo(()=>Math.max(0,Math.min(100,elapsed/duration*100)),[elapsed,duration]);
  const go=(next:number)=>setActive(Math.max(0,Math.min(slides.length-1,next)));
  const switchMode=(next:Mode)=>{setMode(next);setRemaining(next==="pitch"?120:600);setPlaying(false);setActive(0)};
  useEffect(()=>{if(!playing)return;const id=setInterval(()=>setRemaining(v=>{if(v<=1){setPlaying(false);return 0}const next=v-1,per=duration/slides.length,target=Math.min(slides.length-1,Math.floor((duration-next)/per));setActive(target);return next}),1000);return()=>clearInterval(id)},[playing,duration]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(["ArrowRight","ArrowDown","PageDown"].includes(e.key))go(active+1);if(["ArrowLeft","ArrowUp","PageUp"].includes(e.key))go(active-1);if(e.key.toLowerCase()==="n")setNotes(v=>!v);if(e.key===" "){e.preventDefault();setPlaying(v=>!v)}if(e.key.toLowerCase()==="f")document.documentElement.requestFullscreen?.()};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[active]);
  return <main className={`deck mode-${mode} tone-${slide.tone||"ink"}`} onTouchStart={e=>touchStart.current=e.touches[0].clientX} onTouchEnd={e=>{const d=e.changedTouches[0].clientX-touchStart.current;if(Math.abs(d)>55)go(active+(d<0?1:-1))}}>
    <DeckScene slide={active}/><div className="deck-noise"/>
    <header className="deck-topbar"><Mark/><div className="mode-switch" aria-label="Presentation length"><button className={mode==="pitch"?"active":""} onClick={()=>switchMode("pitch")}><b>2:00</b><span>PITCH</span></button><button className={mode==="presentation"?"active":""} onClick={()=>switchMode("presentation")}><b>10:00</b><span>PRESENTATION</span></button></div><div className="deck-actions"><Link href="/prototype">TRY VEGA ↗</Link><button onClick={()=>document.documentElement.requestFullscreen?.()} aria-label="Enter fullscreen">⛶</button></div></header>
    <section key={`${mode}-${active}`} className={`deck-slide slide-${active+1}`}>
      {slide.photo&&<div className="slide-photo">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={slide.photo} alt=""/><i/><small>{slide.credit}</small>
      </div>}
      <div className="slide-copy"><div className="slide-meta"><span>{slide.eyebrow}</span><b>{slide.speaker}</b></div><h1>{slide.title}</h1><div className="slide-body">{mode==="pitch"?slide.short:slide.long}</div>{slide.source&&<a className="slide-source" href={slide.source.url} target="_blank" rel="noreferrer">SOURCE · {slide.source.label} ↗</a>}</div>
      <div className="slide-graphic"><Graphic type={slide.visual} mode={mode}/></div>
      {notes&&<aside className="speaker-note"><span>SPEAKER NOTE</span><p>{slide.note}</p></aside>}
    </section>
    <footer className="deck-controls"><div className="time"><button onClick={()=>setPlaying(v=>!v)} aria-label={playing?"Pause timer":"Start timer"}>{playing?"Ⅱ":"▶"}</button><b>{String(Math.floor(remaining/60)).padStart(2,"0")}:{String(remaining%60).padStart(2,"0")}</b><span>{playing?"LIVE":"READY"}</span></div><div className="slide-dots">{slides.map((_,i)=><button key={i} className={i===active?"active":i<active?"past":""} onClick={()=>go(i)} aria-label={`Go to slide ${i+1}`}><i/></button>)}</div><div className="nav-buttons"><button onClick={()=>setNotes(v=>!v)} className={notes?"active":""}>N · NOTES</button><button onClick={()=>go(active-1)} disabled={active===0}>←</button><b>{String(active+1).padStart(2,"0")} / 10</b><button onClick={()=>go(active+1)} disabled={active===9}>→</button></div><i className="timeline"><span style={{width:`${timeline}%`}}/></i></footer>
  </main>;
}
