"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import "./prototype.css";

type Role="Student"|"Teacher"|"Family"|"Staff";
type Msg={id:number;who:"user"|"vega";text:string;sources?:{name:string;url:string}[];warning?:string};
type Thread={id:string;title:string;role:Role;messages:Msg[];updated:number};
const starter:Thread={id:"welcome",title:"Welcome to VEGA",role:"Student",updated:Date.now(),messages:[{id:1,who:"vega",text:"Hi—I’m the VEGA concept assistant. I can tutor, plan, translate, and help you navigate official CCSD resources. This prototype runs locally in your browser and uses fictional demo data."}]};
const official={
 grades:{name:"Infinite Campus",url:"https://campusportal.ccsd.net/"},canvas:{name:"Canvas",url:"https://canvas.ccsd.net/"},privacy:{name:"CCSD Student Data Privacy",url:"https://safe.ccsd.net/"},policy:{name:"CCSD Acceptable Use Policy",url:"https://www.ccsd.net/legal/acceptable-use-policy"},tech:{name:"CCSD StuTech",url:"https://stutech.ccsd.net/"},transport:{name:"CCSD Transportation",url:"https://transportation.ccsd.net/"}
};
const pii=/\b(?:\d{3}-\d{2}-\d{4}|\d{7,10}|[\w.+-]+@[\w.-]+\.[a-z]{2,}|password|student id|home address|iep|medical record)\b/i;
function response(q:string,role:Role):Omit<Msg,"id"|"who">{
 const s=q.toLowerCase();
 if(pii.test(q))return{text:"I stopped that message because it may contain private information. Remove names, IDs, contact details, passwords, grades, medical information, or education records, then ask again using fictional details.",warning:"Privacy safeguard triggered",sources:[official.privacy]};
 if(/grade|attendance|schedule|campus/.test(s))return{text:"Use Infinite Campus for real-time grades, attendance, schedules, assignments, academic progress, and notices. I can explain how to navigate it, but this prototype cannot see anyone’s record.",sources:[official.grades]};
 if(/canvas|assignment|module|course/.test(s))return{text:"Canvas is CCSD’s learning-management entry point for courses, assignments, modules, and class resources. Students generally access Canvas through Clever. If a course is missing, check All Courses and ask the teacher if it is unpublished.",sources:[official.canvas,{name:"Canvas Help",url:"https://canvashelp.ccsd.net/"}]};
 if(/bus|transport|route/.test(s))return{text:"CCSD Transportation is the official source for routes and eligibility. Don’t post an address here; use the district tool privately or contact the school.",sources:[official.transport]};
 if(/privacy|data|safe|policy|ai rule/.test(s))return{text:"CCSD’s published guidance requires educational use, protection of personally identifiable information, critical review of AI output, and prohibits deceptive content, plagiarism, and sensitive information in external AI tools. VEGA’s local architecture is designed around those requirements, but would still require formal district review.",sources:[official.policy,official.privacy]};
 if(/slope|linear|y\s*=|graph/.test(s))return{text:"Let’s learn it without skipping the thinking. Slope is change in y divided by change in x. Pick two points, subtract their y-values, then subtract their x-values in the same order. What two points do you have?",sources:[{name:"CCSS Mathematics",url:"https://www.thecorestandards.org/Math/Content/8/EE/B/6/"}]};
 if(/essay|write|paragraph|thesis/.test(s))return{text:"I can coach the structure. Start with one sentence that answers the question, then list two pieces of evidence and explain how each supports that answer. Send the prompt—not a completed classmate response—and I’ll ask questions that sharpen your own thesis."};
 if(/quiz|test me|study/.test(s))return{text:"Study mode started. I’ll ask one question at a time, wait for your answer, then give a hint before revealing anything. First: explain the topic in one sentence as if you were teaching a younger student."};
 if(/spanish|translate/.test(s))return{text:"Puedo ayudar a explicar información escolar en español claro. Pegue solo el texto que no contenga nombres, identificaciones, calificaciones ni otra información privada. También mostraré el inglés original para que pueda verificar la traducción."};
 const lead=role==="Teacher"?"I can turn that into a lesson objective, activity, differentiation, and exit ticket.":role==="Family"?"I can explain that in plain language and help draft a respectful school message.":role==="Staff"?"I can map that request to policy, controls, and a measurable pilot workflow.":"I can help you understand it step by step while keeping the work yours.";
 return{text:`${lead} Tell me the subject, goal, and what you have already tried. Don’t include private student information.`};
}
export default function Prototype(){
 const [threads,setThreads]=useState<Thread[]>([starter]),[active,setActive]=useState("welcome"),[input,setInput]=useState(""),[role,setRole]=useState<Role>("Student"),[ready,setReady]=useState(false),[menu,setMenu]=useState(false);
 useEffect(()=>{const raw=localStorage.getItem("vega-demo-threads");if(raw)try{const parsed=JSON.parse(raw) as Thread[];setThreads(parsed);setActive(parsed[0]?.id||"welcome");setRole(parsed[0]?.role||"Student")}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("vega-demo-threads",JSON.stringify(threads.slice(0,12)))},[threads,ready]);
 const thread=threads.find(t=>t.id===active)||threads[0];
 function newThread(nextRole=role){const t:Thread={id:crypto.randomUUID(),title:"New conversation",role:nextRole,updated:Date.now(),messages:[{id:Date.now(),who:"vega",text:`${nextRole} workspace ready. Use fictional or public information only.`}]};setThreads(v=>[t,...v]);setActive(t.id);setRole(nextRole);setMenu(false)}
 function send(e?:FormEvent,preset?:string){e?.preventDefault();const q=(preset||input).trim();if(!q||!thread)return;const now=Date.now(),user:Msg={id:now,who:"user",text:q},reply:Msg={id:now+1,who:"vega",...response(q,role)};setThreads(v=>v.map(t=>t.id===thread.id?{...t,title:t.title==="New conversation"?q.slice(0,36):t.title,role,updated:now,messages:[...t.messages,user,reply]}:t));setInput("")}
 function erase(){if(!thread)return;setThreads(v=>{const n=v.filter(t=>t.id!==thread.id);return n.length?n:[starter]});const n=threads.find(t=>t.id!==thread.id);setActive(n?.id||"welcome")}
 function download(){if(!thread)return;const body=thread.messages.map(m=>`${m.who==="vega"?"VEGA":"YOU"}\n${m.text}`).join("\n\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([body],{type:"text/plain"}));a.download=`vega-${thread.title.replace(/\W+/g,"-").toLowerCase()}.txt`;a.click();URL.revokeObjectURL(a.href)}
 const suggestions=useMemo(()=>role==="Student"?["Tutor me on slope","Start study mode","Where are my grades?"]:role==="Teacher"?["Plan a 45-minute lesson","Make an exit ticket","Summarize AI policy"]:role==="Family"?["Explain an assignment","Translate to Spanish","Where are grades?"]:["Summarize safeguards","Show policy sources","Draft pilot metrics"],[role]);
 return <main className="vega-app">
  <aside className={menu?"side open":"side"}><div className="appbrand"><span>V</span><b>VEGA</b><em>PROTOTYPE</em></div><button className="newchat" onClick={()=>newThread()}>＋ New conversation</button><label>RECENT</label><div className="threads">{threads.sort((a,b)=>b.updated-a.updated).map(t=><button key={t.id} className={t.id===active?"selected":""} onClick={()=>{setActive(t.id);setRole(t.role);setMenu(false)}}><span>◇</span><div><b>{t.title}</b><small>{t.role}</small></div></button>)}</div><div className="system"><b>● LOCAL DEMO READY</b><span>No messages leave this browser</span><small>External model: disconnected</small></div></aside>
  <section className="workspace"><header><button className="menubtn" onClick={()=>setMenu(!menu)}>☰</button><div><b>{thread?.title}</b><span><i/>Protected concept workspace</span></div><div className="header-actions"><select value={role} onChange={e=>{const r=e.target.value as Role;setRole(r);setThreads(v=>v.map(t=>t.id===active?{...t,role:r}:t))}} aria-label="User role"><option>Student</option><option>Teacher</option><option>Family</option><option>Staff</option></select><button onClick={download}>↓ Export</button><button onClick={erase} className="danger">Clear</button></div></header>
   <div className="messages">{thread?.messages.map(m=><article key={m.id} className={m.who}><div className="avatar">{m.who==="vega"?"V":"Y"}</div><div><b>{m.who==="vega"?"VEGA":"YOU"}</b>{m.warning&&<strong className="warning">⚠ {m.warning}</strong>}<p>{m.text}</p>{m.sources&&<div className="source-row"><span>VERIFIED SOURCES</span>{m.sources.map(s=><a href={s.url} target="_blank" key={s.url}>{s.name} ↗</a>)}</div>}</div></article>)}</div>
   <div className="dock"><div className="suggestions">{suggestions.map(s=><button key={s} onClick={()=>send(undefined,s)}>{s}</button>)}</div><form onSubmit={send}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={`Message VEGA as ${role.toLowerCase()}…`} aria-label="Message VEGA"/><button disabled={!input.trim()}>↑</button></form><small><b>Prototype:</b> responses use a local rules engine, not a live AI. Never enter real student data. VEGA can make mistakes—check sources.</small></div>
  </section>
 </main>
}
